version: '3'
services:
  web:
    build: ./
    ports:
      - "82:80"
    depends_on:
      - db
    expose:
      - 9010
    volumes:
      - ./:/var/www/html/
      - ./local/php.ini:/usr/local/etc/php/php.ini
      - ./local/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - ecom_network


  db:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecom_db
      MYSQL_USER: 123456
      MYSQL_PASSWORD: yassine
    volumes:
      - "./db:/var/lib/mysql"
    networks:
      - ecom_network


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8280:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - ecom_network


networks:
  ecom_network:
    driver: bridge